

<!-- Footer -->
<footer class="page-footer font-small">

  <div class="icons row text-center py-3">
      <a href="https://github.com/mbushoy27" target="_blank">
        <i class="icon fab fa-github fa-2x" style="color:white"></i>
      </a>
      <a href="https://www.linkedin.com/in/michelle-bushoy-725730137/" target="_blank">
        <i class="icon fab fa-linkedin fa-2x" style="color:white"></i>
      </a>
      <a href="../images/Resume.pdf" target="_blank">
        <i class="icon fas fa-file fa-2x" style="color:white"></i>
      </a>
  </div>

  <div class="footer text-center">© 2018 Copyright:
    <a> Michelle Bushoy</a>
  </div>

  </footer>

